### ISSUE TITLE
Include a compiled CSS file of the less files in the package.

### ISSUE THREAD

**Issue by rlmcneary2** [donejs/place-my-order-assets#4]
To allow for the broadest usage include a single compiled CSS file built from the less files. This is only needed in the package so it should be done as a build before publish step and not committed to the repository.

**Comment by justinbmeyer** [comment]
Here is how we've gotten a release script to build and commit to a `release` branch: 

https://github.com/canjs/can-ejs/blob/8f3ef7096c00bdd8ea67e7a7932a47b8087fa110/package.json#L12

**Comment by rlmcneary2** [comment]
Resolved by pr #6
